### ISSUE TITLE
Add support for downloading a category

### ISSUE THREAD

**Issue by JeanFred** [Commonists/CommonsDownloader#9]
As a user, I want to download all images in a given Commons category.

**Comment by JeanFred** [comment]
Should be fairly easy to implement. A quick call to the API categorymembers and looping over the results. Probably want to filter out videos and GIFs? By MIME type?

**Comment by PierreSelim** [comment]
Not sure it's so "easy to call the API because ... you have to loop over the "continue" result for large categories which is pretty boring :)

**Comment by PierreSelim** [comment]
Tested on `download_from_wikimedia_commons --category 'Media supported by Wikimedia France - Sèvres' --width 2000` it works http://commonists.org/wmfr_sevres.tar.bz2

**Comment by JeanFred** [comment]
@pierreselim Did you check the console logs ? Since 7dad7e6 and 3e1c728 CommonsDownloader will not crash when choking on a single file. And i think there should be choking files in there (like videos)
